spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver

message: "Git Message"
secretMessage: '{cipher}edcb24a39d1e0df8c80ee29cc1d54916861e3886ea5c760bd758a4196f677e10'
