message: Hello from Git

spring:
  application:
    exchange: product.events.fanout.exchange
    queue: product.default.queue
    databaseName: products
    eventsCollectionName: events
    snapshotCollectionName: snapshots

external:
  amqp:
    exchange:
      fanout:
        auto-delete: false
    bind:
      route-key: "*"
    queue: product.default.queue
  event-sourcing:
        events-collection-name: service-events
        snapshot-collection-name: service-events-snapshots
