message: Hello from Git

spring:
  application:
    exchange: product.events.fanout.exchange
    queue: product.default.queue
    databaseName: products
    eventsCollectionName: events
    snapshotCollectionName: snapshots

#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/products
