message: Hello from Git

spring:
  application:
    exchange: product.events.fanout.exchange
    queue: product.default.queue
    eventsCollectionName: events
    snapshotCollectionName: snapshots
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL  
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

axon:
  amqp:
    exchange: product.events.fanout.exchange
    transaction-mode: none
    durable-messages: true
    
external:
  amqp:
    exchange:
      fanout:
        auto-delete: false
    bind:
      route-key: "*"
    queue: product.default.queue
  event-sourcing:
        events-collection-name: service-events
        snapshot-collection-name: service-events-snapshots
