management:
  security:
    enabled: false

---

spring:
  profiles: original
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver

---

spring:
  profiles: sso
security:
  oauth2:
   client:
     client-id: f17dfc29-7c0f-4e50-af2c-06a21b670fd0
     client-secret: 7c7aafa6-18ff-4d37-9e20-3a7dd34d975a
eureka:
  client:
    enabled: true
hystrix.command.default.execution.isolation.strategy: SEMAPHORE