secretMessage: '{cipher}edcb24a39d1e0df8c80ee29cc1d54916861e3886ea5c760bd758a4196f677e10'

---

spring:
  profiles: cloud
  cloud:
    config:
      enabled: true

eureka:
  client:
    enabled: true
